In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

## Data Collection

### Files sources

In [2]:
import requests

# URLs of the files
train_data_url_StoreA = 'https://www.raphaelcousin.com/modules/module4/course/CityMart_data.csv'
train_data_url_StoreB = 'https://www.raphaelcousin.com/modules/module4/course/Greenfield Grocers_data.csv'
train_data_url_StoreC = 'https://www.raphaelcousin.com/modules/module4/course/SuperSaver Outlet_data.xlsx'
train_data_url_StoreD = 'https://www.raphaelcousin.com/modules/module4/course/HighStreet Bazaar_data.json'

test_data_url = 'https://www.raphaelcousin.com/modules/module3/course/Neighborhood Market_data.csv'

# Function to download a file
def download_file(url, file_name):
    response = requests.get(url)
    response.raise_for_status()  # Ensure we notice bad responses
    with open(file_name, 'wb') as file:
        file.write(response.content)
    print(f'Downloaded {file_name} from {url}')

# Downloading the files
download_file(train_data_url_StoreA, 'CityMart_data.csv')
download_file(train_data_url_StoreB, 'Greenfield Grocers_data.csv')
download_file(train_data_url_StoreC, 'SuperSaver Outlet_data.xlsx')
download_file(train_data_url_StoreD, 'HighStreet Bazaar_data.json')

download_file(test_data_url, 'Neighborhood Market_data.csv')

Downloaded StoreA_data.csv from https://www.raphaelcousin.com/modules/module4/course/StoreA_data.csv
Downloaded StoreB_data.csv from https://www.raphaelcousin.com/modules/module4/course/StoreB_data.csv
Downloaded StoreC_data.xlsx from https://www.raphaelcousin.com/modules/module4/course/StoreC_data.xlsx
Downloaded StoreD_data.json from https://www.raphaelcousin.com/modules/module4/course/StoreD_data.json
Downloaded StoreE_data.csv from https://www.raphaelcousin.com/modules/module3/course/StoreE_data.csv

#### CityMart

In [3]:
# read
df_StoreA =  pd.read_csv("StoreA_data.csv", sep=",", index_col='product_id')
df_StoreA

,store,weight,length,width,days_since_last_sale,days_in_stock,price,number_sold,last_updated
product_id,,,,,,,,,
P0019,StoreA,8.71,12.81,58.68,190,651,17.23,214,2023-01-19
P0024,StoreA,3.42,41.28,38.92,115,317,10.63,188,2023-01-24
P0025,StoreA,8.05,24.54,92.99,337,123,21.49,176,2023-01-25
P0034,StoreA,4.58,32.82,7.77,85,717,7.68,169,2023-02-03
P0039,StoreA,5.03,82.12,42.79,266,542,7.71,193,2023-02-08
...,...,...,...,...,...,...,...,...,...
P0956,StoreA,2.23,69.04,91.37,168,38,12.37,115,2025-08-13
P0960,StoreA,8.04,32.60,23.11,163,571,16.67,131,2025-08-17
P0967,StoreA,1.07,64.94,55.49,84,569,1.00,192,2025-08-24
P0997,StoreA,5.17,59.11,61.51,316,366,15.79,90,2025-09-23
P0998,StoreA,6.83,29.66,75.19,265,420,20.90,206,2025-09-24

#### Greenfield Grocers

In [4]:
# read
df_StoreB =  pd.read_csv("StoreB_data.csv", sep=";", header=1, index_col='PRODUCT_ID')
df_StoreB

,STORE,WEIGHT,LENGTH,WIDTH,DAYS_SINCE_LAST_SALE,DAYS_IN_STOCK,PRICE,NUMBER_SOLD,LAST_UPDATED,Unnamed: 10
PRODUCT_ID,,,,,,,,,,
P0006,StoreB,1.61,75.06,91.25,301,783.0,8.26,220,2023-01-06,NaN
P0014,StoreB,1.22,14.35,73.24,272,657.0,6.84,71,2023-01-14,NaN
P0016,StoreB,8.41,77.62,65.86,255,866.0,16.70,119,2023-01-16,NaN
P0021,StoreB,5.95,33.07,52.40,24,810.0,17.04,126,2023-01-21,NaN
P0028,StoreB,4.04,78.59,26.10,136,593.0,6.23,94,2023-01-28,NaN
...,...,...,...,...,...,...,...,...,...,...
P0984,StoreB,8.42,24.87,90.35,276,490.0,8.24,171,2025-09-10,NaN
P0990,StoreB,8.96,27.99,14.92,342,413.0,12.90,136,2025-09-16,NaN
P0991,StoreB,6.40,96.26,59.80,104,434.0,15.06,168,2025-09-17,NaN
P0994,StoreB,5.23,99.51,98.15,32,952.0,19.71,195,2025-09-20,NaN
P0996,StoreB,7.40,98.21,11.39,230,956.0,11.50,83,2025-09-22,NaN

In [5]:
# format
df_StoreB.drop('Unnamed: 10', axis=1, inplace=True)
df_StoreB.columns = [col.lower() for col in df_StoreB.columns]
df_StoreB.rename_axis(df_StoreB.index.name.lower(), inplace=True)
df_StoreB

,store,weight,length,width,days_since_last_sale,days_in_stock,price,number_sold,last_updated
product_id,,,,,,,,,
P0006,StoreB,1.61,75.06,91.25,301,783.0,8.26,220,2023-01-06
P0014,StoreB,1.22,14.35,73.24,272,657.0,6.84,71,2023-01-14
P0016,StoreB,8.41,77.62,65.86,255,866.0,16.70,119,2023-01-16
P0021,StoreB,5.95,33.07,52.40,24,810.0,17.04,126,2023-01-21
P0028,StoreB,4.04,78.59,26.10,136,593.0,6.23,94,2023-01-28
...,...,...,...,...,...,...,...,...,...
P0984,StoreB,8.42,24.87,90.35,276,490.0,8.24,171,2025-09-10
P0990,StoreB,8.96,27.99,14.92,342,413.0,12.90,136,2025-09-16
P0991,StoreB,6.40,96.26,59.80,104,434.0,15.06,168,2025-09-17
P0994,StoreB,5.23,99.51,98.15,32,952.0,19.71,195,2025-09-20
P0996,StoreB,7.40,98.21,11.39,230,956.0,11.50,83,2025-09-22

#### Outlet_data

In [6]:
# read
df_StoreCs =  pd.read_excel("StoreC_data.xlsx", sheet_name=None)
df_StoreCs

{'Sheet1':     product_id  number_sold
 0        P0003           28
 1        P0007           26
 2        P0008           34
 3        P0009           17
 4        P0012            9
 ..         ...          ...
 185      P0985           46
 186      P0986           25
 187      P0989           12
 188      P0992            3
 189      P1000           54

 [190 rows x 2 columns],
 'Sheet2':     product id   store  weight  length  width  days_since_last_sale  \
 0        P0003  StoreC    7.00   11.77  98.21                   120
 1        P0007  StoreC    5.81   38.56  94.65                   254
 2        P0008  StoreC    6.11   33.17  96.21                   121
 3        P0009  StoreC    4.30   38.22  54.54                    30
 4        P0012  StoreC    9.26   22.59  20.36                   105
 ..         ...     ...     ...     ...    ...                   ...
 185      P0985  StoreC    0.48    9.75  42.95                    64
 186      P0986  StoreC    9.03   85.15  36.05                   270
 187      P0989  StoreC    6.63   86.11  81.09                   137
 188      P0992  StoreC    6.18   23.71  49.08                    33
 189      P1000  StoreC    0.94   61.39  67.58                   339

      days_in_stock  price
 0            513.0  17.85
 1            753.0  11.94
 2            540.0   7.24
 3            735.0   8.37
 4            621.0  16.36
 ..             ...    ...
 185          746.0   3.85
 186          643.0  19.46
 187          316.0   9.98
 188            2.0  10.66
 189          785.0   1.97

 [190 rows x 8 columns]}

In [7]:
# format
df_StoreC = pd.merge(df_StoreCs['Sheet1'], df_StoreCs['Sheet2'], left_on = 'product_id' , right_on = 'product id')
df_StoreC = df_StoreC[['product_id', 'store', 'weight', 'length', 'width', 'days_since_last_sale', 'days_in_stock',	'price']]
df_StoreC.set_index('product_id', inplace=True)
df_StoreC

,store,weight,length,width,days_since_last_sale,days_in_stock,price
product_id,,,,,,,
P0003,StoreC,7.00,11.77,98.21,120,513.0,17.85
P0007,StoreC,5.81,38.56,94.65,254,753.0,11.94
P0008,StoreC,6.11,33.17,96.21,121,540.0,7.24
P0009,StoreC,4.30,38.22,54.54,30,735.0,8.37
P0012,StoreC,9.26,22.59,20.36,105,621.0,16.36
...,...,...,...,...,...,...,...
P0985,StoreC,0.48,9.75,42.95,64,746.0,3.85
P0986,StoreC,9.03,85.15,36.05,270,643.0,19.46
P0989,StoreC,6.63,86.11,81.09,137,316.0,9.98
P0992,StoreC,6.18,23.71,49.08,33,2.0,10.66
P1000,StoreC,0.94,61.39,67.58,339,785.0,1.97

#### HighStreet Bazaar

In [8]:
# read
df_StoreD = pd.read_json('StoreD_data.json', orient='records')
df_StoreD

,product_id,store,weight,length,width,days_since_last_sale,days_in_stock,price,number_sold,last_updated
0,P0001,StoreD,9.33,73.05,11.94,236,65.0,12.00,40,1672531200000
1,P0011,StoreD,9.35,67.83,76.94,284,496.0,15.07,42,1673395200000
2,P0015,StoreD,9.85,67.73,28.50,231,369.0,13.11,30,1673740800000
3,P0017,StoreD,1.33,30.18,68.33,23,909.0,3.21,54,1673913600000
4,P0020,StoreD,5.24,96.95,78.30,346,796.0,9.94,65,1674172800000
...,...,...,...,...,...,...,...,...,...,...
201,P0982,StoreD,4.43,20.75,58.83,256,257.0,9.67,34,1757289600000
202,P0983,StoreD,2.62,47.33,67.42,294,672.0,6.90,30,1757376000000
203,P0988,StoreD,6.41,80.35,83.52,316,659.0,NaN,72,1757808000000
204,P0993,StoreD,0.76,95.39,16.28,109,841.0,11.28,78,1758240000000
205,P0999,StoreD,0.51,46.51,8.08,181,573.0,4.04,36,1758758400000

In [9]:
# format
df_StoreD.set_index('product_id', inplace=True)
df_StoreD

,store,weight,length,width,days_since_last_sale,days_in_stock,price,number_sold,last_updated
product_id,,,,,,,,,
P0001,StoreD,9.33,73.05,11.94,236,65.0,12.00,40,1672531200000
P0011,StoreD,9.35,67.83,76.94,284,496.0,15.07,42,1673395200000
P0015,StoreD,9.85,67.73,28.50,231,369.0,13.11,30,1673740800000
P0017,StoreD,1.33,30.18,68.33,23,909.0,3.21,54,1673913600000
P0020,StoreD,5.24,96.95,78.30,346,796.0,9.94,65,1674172800000
...,...,...,...,...,...,...,...,...,...
P0982,StoreD,4.43,20.75,58.83,256,257.0,9.67,34,1757289600000
P0983,StoreD,2.62,47.33,67.42,294,672.0,6.90,30,1757376000000
P0988,StoreD,6.41,80.35,83.52,316,659.0,NaN,72,1757808000000
P0993,StoreD,0.76,95.39,16.28,109,841.0,11.28,78,1758240000000
P0999,StoreD,0.51,46.51,8.08,181,573.0,4.04,36,1758758400000

#### Aggregate

In [10]:
data = pd.concat([df_StoreA, df_StoreB, df_StoreC, df_StoreD], axis=0)
data

,store,weight,length,width,days_since_last_sale,days_in_stock,price,number_sold,last_updated
product_id,,,,,,,,,
P0019,StoreA,8.71,12.81,58.68,190,651.0,17.23,214.0,2023-01-19
P0024,StoreA,3.42,41.28,38.92,115,317.0,10.63,188.0,2023-01-24
P0025,StoreA,8.05,24.54,92.99,337,123.0,21.49,176.0,2023-01-25
P0034,StoreA,4.58,32.82,7.77,85,717.0,7.68,169.0,2023-02-03
P0039,StoreA,5.03,82.12,42.79,266,542.0,7.71,193.0,2023-02-08
...,...,...,...,...,...,...,...,...,...
P0982,StoreD,4.43,20.75,58.83,256,257.0,9.67,34.0,1757289600000
P0983,StoreD,2.62,47.33,67.42,294,672.0,6.90,30.0,1757376000000
P0988,StoreD,6.41,80.35,83.52,316,659.0,NaN,72.0,1757808000000
P0993,StoreD,0.76,95.39,16.28,109,841.0,11.28,78.0,1758240000000
P0999,StoreD,0.51,46.51,8.08,181,573.0,4.04,36.0,1758758400000

#### Simple baseline

In [11]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, accuracy_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import numpy as np

def get_simple_baseline(data, fillna_value=-1, drop_cols=None, k_fold=5, scaler='standard', model='linear', metric='mae', target_col=None):
    data = data.copy()
    # Handle missing values
    data.fillna(fillna_value, inplace=True)
    
    # Drop unwanted columns
    if drop_cols:
        data.drop(drop_cols, axis=1, inplace=True)

    # Split data into features (X) and target (y)
    y = data[target_col]
    X = data.drop(target_col, axis=1)

    # Feature scaling
    if scaler == 'standard':
        scaler = StandardScaler()
    elif scaler == 'minmax':
        scaler = MinMaxScaler()
    else:
        scaler = None
    
    if scaler:
        X = scaler.fit_transform(X)

    # Initialize the model
    if model == 'linear':
        model = LinearRegression()
    elif model == 'logistic':
        model = LogisticRegression()
    elif model == 'random_forest':
        model = RandomForestClassifier()
    else:
        raise ValueError("Unsupported model type")

    # Initialize cross-validation
    kf = KFold(n_splits=k_fold, shuffle=True, random_state=42)
    scores = []

    # Train and evaluate using k-fold cross-validation
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        
        # Train the model
        model.fit(X_train, y_train)
        
        # Make predictions
        y_pred = model.predict(X_test)
        
        # Evaluate using the specified metric
        if metric == 'mae':
            score = mean_absolute_error(y_test, y_pred)
        elif metric == 'accuracy':
            score = accuracy_score(y_test, np.round(y_pred))
        else:
            raise ValueError("Unsupported metric")

        scores.append(score)
    
    # Return the average score
    return np.mean(scores)

In [12]:
get_simple_baseline(data, fillna_value=-1, drop_cols=['store', 'last_updated'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='number_sold')

64.0364557553227

### API sources

In [13]:
def get_api(endpoint_url):
    try:
        # Make the GET request to the mock API
        response = requests.get(endpoint_url)

        if response.status_code == 200:
            data = response.json()
            print(data["message"])
            return data['data']
        else:
            print(f"Failed to retrieve volume data. Status code: {response.status_code}")
    
    except Exception as e:
        print(f"An error occurred: {e}")
password = get_api("https://www.raphaelcousin.com/api/course/auth")["password"]
volumes = get_api(f"https://www.raphaelcousin.com/api/course/{password}/volumes")

Authentication successful
Volume data retrieved successfully

In [14]:
df_volumes = pd.DataFrame.from_dict(volumes, orient='index', columns=['volume'])

In [15]:
df_volumes

              volume
P0001   48469.098690
P0002   11252.963820
P0003   24725.379063
P0004    8361.648240
P0005  255200.667150
...              ...
P0996  106905.739283
P0997   38976.377392
P0998   74218.906112
P0999   12521.682656
P1000  147031.210928

[1000 rows x 1 columns]

#### Aggregate

In [16]:
data = pd.merge(data, df_volumes, left_index=True, right_index=True, how='left')
data

,store,weight,length,width,days_since_last_sale,days_in_stock,price,number_sold,last_updated,volume
product_id,,,,,,,,,,
P0019,StoreA,8.71,12.81,58.68,190,651.0,17.23,214.0,2023-01-19,21814.067016
P0024,StoreA,3.42,41.28,38.92,115,317.0,10.63,188.0,2023-01-24,80893.196160
P0025,StoreA,8.05,24.54,92.99,337,123.0,21.49,176.0,2023-01-25,87468.086418
P0034,StoreA,4.58,32.82,7.77,85,717.0,7.68,169.0,2023-02-03,6635.396628
P0039,StoreA,5.03,82.12,42.79,266,542.0,7.71,193.0,2023-02-08,170846.537576
...,...,...,...,...,...,...,...,...,...,...
P0982,StoreD,4.43,20.75,58.83,256,257.0,9.67,34.0,1757289600000,41797.538400
P0983,StoreD,2.62,47.33,67.42,294,672.0,6.90,30.0,1757376000000,89060.491826
P0988,StoreD,6.41,80.35,83.52,316,659.0,NaN,72.0,1757808000000,219309.989760
P0993,StoreD,0.76,95.39,16.28,109,841.0,11.28,78.0,1758240000000,80489.357036
P0999,StoreD,0.51,46.51,8.08,181,573.0,4.04,36.0,1758758400000,12521.682656

In [17]:
get_simple_baseline(data, fillna_value=-1, drop_cols=['store', 'last_updated'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='number_sold')

63.495291068410175

### Scrapping sources

In [26]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

# Set up the Selenium WebDriver (e.g., Chrome)
driver = webdriver.Chrome()  # Make sure ChromeDriver is installed
# driver = webdriver.Firefox()
# driver = webdriver.Edge()
# driver = webdriver.Safari()

# Open the URL
url = 'https://www.raphaelcousin.com/module4/scrapable-data'
driver.get(url)

# Wait for the page to fully load (increase time if needed)
time.sleep(5)

# Get the fully rendered page source
html = driver.page_source

# Parse the HTML with BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Initialize lists to store scraped data
course_data = []
exercise_data = []

# Find both tables
tables = soup.find_all('table')

# Close the Selenium WebDriver
driver.quit()

# Scrape the first table (Course Data)
course_table = tables[0]
for row in course_table.find('tbody').find_all('tr'):
    cols = row.find_all('td')
    course_data.append({
        'Product ID': cols[0].text,
        'Rating': float(cols[1].text),
        'Number of Reviews': int(cols[2].text),
        'Random Feature': cols[3].text
    })

# Convert the lists to pandas DataFrames
df_course = pd.DataFrame(course_data)
df_course

    Product ID  Rating  Number of Reviews Random Feature
0        P0001     1.0                897             17
1        P0002     3.0                209             26
2        P0003     3.0                125             34
3        P0004     1.0                491             67
4        P0005     4.0                508             77
..         ...     ...                ...            ...
995      P0996     1.0                100             73
996      P0997     3.0                197             14
997      P0998     4.0                812              6
998      P0999     3.0                225             78
999      P1000     3.0                942             81

[1000 rows x 4 columns]

In [27]:
### format
df_course.set_index('Product ID', inplace=True)
df_course.drop('Random Feature', axis=1, inplace=True)

#### Aggregate

In [30]:
data = pd.merge(data, df_course, left_index=True, right_index=True, how='left')

In [31]:
get_simple_baseline(data, fillna_value=-1, drop_cols=['store', 'last_updated'], k_fold=5, scaler='standard', model='linear', metric='mae', target_col='number_sold')

62.512958198288935

### Generating Submission File

In [ ]:
# X_test =  read Neighborhood Market_data.csv

In [ ]:
submission = pd.DataFrame({
    'item_code': X_test.index,
    'quantity_sold': 0 # your_prediction
})

submission.to_csv('submission.csv', index=False, sep=',')
submission.head()